### ISSUE TITLE
Annotations are shown incorrectly

### ISSUE THREAD

**Issue by dlangenk** [biigle/annotations#137]
Annotations are shifted to the right/left/top/bottom when you do the following:

1. Go to https://biigle.de/volumes/2235
2. View any annotation
3. Change the zoom-level r in the url to less than the allowed value e.g. 20
4. Sometimes you have to change to a different image

**Comment by dlangenk** [comment]
Most probably the problem is independent from the zoom issue but more pen related. Almost all of my Ipad made annotations are flawed. (same volume as above)

**Comment by mzur** [comment]
> Almost all of my Ipad made annotations are flawed. (same volume as above)

But not permanently, right?

**Comment by dlangenk** [comment]
It seemed so.  A few minutes ago I checked again and most were flawed. However, I had to redo one annotation. After this all the annotations are fine again. Furthermore it seems to be only a display problem as the largo patches look fine.
