### ISSUE TITLE
Image is not drawn if minimap is closed

### ISSUE THREAD

**Issue by mzur** [biigle/annotations#144]
If the annotation tool is initially opened and the minimap is closed, the image is not rendered. The console shows the error:

```
uncaught exception: AssertionError: Assertion failed. See https://openlayers.org/en/v5.3.0/doc/errors/#1 for details.
```

**Comment by dlangenk** [comment]
Ah, that was the bug we couldn't reproduce on your computer back then because we didn't know about the minimap. But I can confirm the behaviour and error.
